### PR TITLE
Web client/server separately

### PR DESCRIPTION
**Pull request by ashalkhakov**
I've made some changes here, mainly for Linux compatibility. Initially I started working on this because we hit #63, and I thought that it was due to the `Web` assembly being too big. :-)

* if tests are run on non-Windows, then SQL Server for Linux can be used instead of LocalDB (previously tests simply failed)
  * to create this container in Docker: `docker run -e 'ACCEPT_EULA=Y' -e 'SA_PASSWORD=QWE123qwe' -e 'MSSQL_PID=Express' -p 1433:1433 -d microsoft/mssql-server-linux:latest`
* again on Linux, it's easy to test against MySQL if container is created in docker like this:
    * `docker run --name mysql -p 3306 -e 'MYSQL_ROOT_PASSWORD=azerty31$' -d mysql:latest --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --lower-case-table-names=1`
    * we set `lower_case_table_names`, otherwise `MySqlSyncForeignKeysTests` fail due to case-sensitivity of identifiers, which are lower-cased by `Dotmim.Sync`

### CODE REVIEW

**Comment by ashalkhakov** [comment]
Next step: add a Xamarin-based Android app.

**Comment by Mimetis** [comment]
Why split in two projects ? (client / server)
I mean, I didn't check everything for now (hollidayyyyyyyyyys) but it seems that both projects have the exact same references on asp.net core / mvc / session

So why the split ?

Sebastien

**Comment by ashalkhakov** [comment]
You are correct, I forgot to remove them! Could you take a look now?

**Comment by ashalkhakov** [comment]
> I try to keep the less projects as possible. Is it possible to have only two projects : Web.Client and Web.Server ?

Sure, let's trim it down.

> For now I have a problem with the Microsoft.Net.Http.Headers reference.

Yeah, we just hit this on a Windows machine. I'm looking into this.

**Comment by ashalkhakov** [comment]
Thanks! Now we can move forward with a Xamarin test app!

**Pull request merged**
