### PR TITLE
Add composite foreign-keys support 

### PR DESCRIPTION
**Pull request by workgroupengineering**
- Add support composite foreign key
- Raname tests namespace
- fixed issue o f *BuilderTable.BuildForeignKeyConstraintsCommand
- Add test for composite foreign key

### CODE REVIEW

**Comment by Mimetis** [comment]
Hey @workgroupengineering !
Thx for your PR.   
Well, I have several suggestions in mind, looking your PR.

### test project
First one, I'm very sorry that you have spent your time on the test project...   
I have remade the whole project (took me one week) from scratch to have something more, let say.. robust !    
You can read this wiki page about the test project (work in progress) : [Unit Tests. How it works](https://github.com/Mimetis/Dotmim.Sync/wiki/Unit-tests-project.-How-it-works)  
By the way, if you're interested, do not hesitate to browse the code and make any suggestion !

### child - parent relation
Second one, about the support of **composite foreign key**.
I notice you changed a lot of things to make it work (thanks a lot !) but i don't understand why you have inverted the `Parent` - `Child` hierarchy ?

For example, let's say in `SqlBuilderTable.cs`, I see those changes:

```csharp
stringBuilder.AppendLine(parentTableName.FullQuotedString); 
```
replaced by 
```csharp
stringBuilder.AppendLine(childTableName.FullQuotedString); 
```

```csharp
foreach (var parentdColumn in foreignKey.ParentColumns) 
{
          var parentColumnName = new ObjectNameParser(parentdColumn.ColumnName); 
          stringBuilder.Append($"{empty} {parentColumnName.FullQuotedString}"); 
```
replaced by

```csharp
foreach (var childColumn in foreignKey.ChildColumns) 
{ 
        var childColumnName = new ObjectNameParser(childColumn.ColumnName); 
```

### Open connection

In all builders, you add this code
``` csharp
if (sqlConnection.State == ConnectionState.Closed) 
{ 
             sqlConnection.Open(); 
} 
```
The connection is managed by the high level component.   
I guess this is something that already worked since a long time, so why do you need this ?

#### Split PR

To be able to merge your PR and have a discussion on it, it's preferable to make one PR per feature.   
In you case, you have two features implemented : 
- Refactoring tests (that will be rejected for the reasons explained) 
- Composite Foreign key

I think you should have to merge your PR from the master branch to be able to continue 
And let us continue the discussion on architectural and code review :)

And the most important of everything : thanks you for all your time shared on this little project !

**Comment by workgroupengineering** [comment]
Hi,
I have inverted the Parent - Child hierarchy because
there are problems of constraint violation when the relationship is one to many.
MySql, Sqlite and SqlServer specifications indicate, that
FOREIGN KEY must be the columns of the secondary table (Childs)
REFERENCES refers to the table that has the primary key (Parent).

I will refactoring pr.

**Comment by workgroupengineering** [comment]
I did the refactoring and rebasing on master branch of the PR. In the next days after having studied the new Unit Test, I will added the tests.

**Comment by Mimetis** [comment]
Nice !!
The Unit test is pretty simple to implement. 
Just add two new entities, with a double relation in the AdventureWorks EF context.
I Guess it will be enough.

For my advice, Can you point me on where you found the doc and convention about Parent - Child convention ?

**Comment by workgroupengineering** [comment]
Hi,
Thanks for the explanation on the Unit Test.
Documents are here:
- [MySql](https://dev.mysql.com/doc/refman/5.6/en/create-table-foreign-keys.html)
- [Sqlite](https://www.sqlite.org/foreignkeys.html)
- SqlServer In SqlServer I did not find where it is specified but from the tests I made it is same behaves of Sqlite and MySql.

**Comment by Mimetis** [comment]
If you need some help to make the unit tests, in the test project, do not hesitate to discuss it here

**Comment by workgroupengineering** [comment]
Hi,
I have rebase on master branch and fixed typo.

For yours consideration on tests.

I prefer to keep entity mapping and seeding of  the data separate , because it helps keep their focus on context.

>In my opinion, your method is really interesting, but it could be potentially hard to understand, espcially for contributors who just want to add one entity.

In my opinion it is very simple. Because he does not know the inside of the test.
The developer must add three classes:

The definition of entities:
```csharp
class MyEntity
{
  public Guid Code {get; set;}
  public Description {get;set;}
}
```
The configuration:
```csharp
class MyEntityConfig:BaseEntityTypeConfiguration<MyEntity>
{
   public override void Configure(EntityTypeBuilder<PriceListCategory> builder)
   {
      //if this method is empty using default mapping conventions
   }
}
```
The AdventureWorksContext partial class to add the navigation property:

```csharp
    partial class AdventureWorksContext
    {
        public virtual DbSet<MyEntity> MyEntites{ get; set; }
    }
```

One thing I have to understand how to do and change OnConfiguring <T> to update sqlTables and mySqlTables without changing the source code.

**Comment by Mimetis** [comment]
Ok. We can try. Curious to see on the whole database

**Comment by workgroupengineering** [comment]
I removed the dynamic loading of the models and added the test for the composite foreign key

**Comment by Mimetis** [comment]
THX @workgroupengineering  for your amazing amount of work on this feature.
It's just awesome !
Thx for all :)

**Comment by workgroupengineering** [comment]
THX @Mimetis for the fantastic library.

**Comment by Thaval** [comment]
Hey, sorry for crashing in here.
The current version (it's 0.3.0 beta 0156) does not allow me synchronize some of my tables. I looked at the structure of my table and it seems to be that the reason might be the composite keys (CK). I have several CKs and one column which is not a CK.
The thing is that I get an error saying that my table must have at least on primary key. So it's like my CKs are not recognized as PKs at all. The concrete error is:

> Dotmim.Sync.SyncException: 'Table X must have at least one dmColumn as Primary key'


We use Code First approach and generate the CKs with the fluent API (as it's supposed to be done when using more than one composite key).

**Comment by Mimetis** [comment]
Can you share the schema of your db ?

**Comment by Thaval** [comment]
Sure. The generated code is:

> CREATE TABLE [dbo].[ObjectSettingValues] (
>     [ObjectId]     NVARCHAR (450)   NOT NULL,
>     [ObjectType]   NVARCHAR (450)   NOT NULL,
>     [OverrideId]   UNIQUEIDENTIFIER NOT NULL,
>     [OverrideType] NVARCHAR (450)   NOT NULL,
>     [SettingKey]   NVARCHAR (450)   NOT NULL,
>     [Value]        NVARCHAR (MAX)   NULL,
>     CONSTRAINT [PK_ObjectSettingValues] PRIMARY KEY CLUSTERED ([ObjectId] ASC, [ObjectType] ASC, [OverrideId] ASC, [OverrideType] ASC, [SettingKey] ASC),
>     CONSTRAINT [FK_ObjectSettingValues_ObjectSettings_ObjectType_SettingKey] FOREIGN KEY ([ObjectType], [SettingKey]) REFERENCES [dbo].[ObjectSettings] ([ObjectType], [SettingKey]) ON DELETE CASCADE
> );
> 
> 
> GO
> CREATE NONCLUSTERED INDEX [IX_ObjectSettingValues_ObjectType_SettingKey]
>     ON [dbo].[ObjectSettingValues]([ObjectType] ASC, [SettingKey] ASC);

(sry, got formation troubles when using code format)


And a screenshot of the table scheme within VS17:

table_scheme

**Comment by Mimetis** [comment]
Thx !
It's enough to make some tests :)

**Comment by Mimetis** [comment]
Hello @Thaval 
I've just made a quick test with your schema (I just had to add a new table called `ObjectSettings`)

Here is the script I used:

``` sql
USE [master]
GO 

-- Server database
if (exists (select * from sys.databases where name = 'OptionsServer'))
begin
	ALTER DATABASE OptionsServer SET  SINGLE_USER WITH ROLLBACK IMMEDIATE;
	DROP DATABASE OptionsServer
End
Create database OptionsServer
Go
-- Client database. No need to create the schema, Dotmim.Sync will do
if (exists (select * from sys.databases where name = 'OptionsClient'))
begin
	ALTER DATABASE OptionsClient SET  SINGLE_USER WITH ROLLBACK IMMEDIATE;
	DROP DATABASE OptionsClient
End
Create database OptionsClient
GO

Use OptionsServer;
GO

CREATE TABLE [ObjectSettings](
[ObjectType]   NVARCHAR (450)   NOT NULL,
[SettingKey]   NVARCHAR (450)   NOT NULL,
[Value]		   NVARCHAR (MAX)   NULL,
CONSTRAINT [PK_ObjectSetting] PRIMARY KEY CLUSTERED ([ObjectType] ASC, [SettingKey] ASC),

)

CREATE TABLE [dbo].[ObjectSettingValues] (
[ObjectId]     NVARCHAR (450)   NOT NULL,
[ObjectType]   NVARCHAR (450)   NOT NULL,
[OverrideId]   UNIQUEIDENTIFIER NOT NULL,
[OverrideType] NVARCHAR (450)   NOT NULL,
[SettingKey]   NVARCHAR (450)   NOT NULL,
[Value]        NVARCHAR (MAX)   NULL,
CONSTRAINT [PK_ObjectSettingValues] PRIMARY KEY CLUSTERED ([ObjectId] ASC, [ObjectType] ASC, [OverrideId] ASC, [OverrideType] ASC, [SettingKey] ASC),
CONSTRAINT [FK_ObjectSettingValues_ObjectSettings_ObjectType_SettingKey] FOREIGN KEY ([ObjectType], [SettingKey]) REFERENCES [dbo].[ObjectSettings] ([ObjectType], [SettingKey]) ON DELETE CASCADE
);
GO
CREATE NONCLUSTERED INDEX [IX_ObjectSettingValues_ObjectType_SettingKey]
ON [dbo].[ObjectSettingValues]([ObjectType] ASC, [SettingKey] ASC);


INSERT INTO [ObjectSettings] ([ObjectType], [SettingKey], [Value])
VALUES ('T1', 'ST1', 'a random value');

INSERT INTO [ObjectSettingValues] ([ObjectId], [ObjectType], [OverrideId], [OverrideType], [SettingKey], [Value])
VALUES ('SST1', 'T1', newid(), 'OVERRIDE SST1',  'ST1', 'a random value 1');

INSERT INTO [ObjectSettingValues] ([ObjectId], [ObjectType], [OverrideId], [OverrideType], [SettingKey], [Value])
VALUES ('SST2', 'T1', newid(), 'OVERRIDE SST1',  'ST1', 'a random value 2');

```
Then, here is the code I used to sync:

``` csharp
// Create 2 Sql Sync providers
var serverProvider = new SqlSyncProvider(DbHelper.GetDatabaseConnectionString("OptionsServer"));
var clientProvider = new SqlSyncProvider(DbHelper.GetDatabaseConnectionString("OptionsClient"));

// Tables involved in the sync process:
var tables = new string[] { "ObjectSettings", "ObjectSettingValues" };

// Creating an agent that will handle all the process
var agent = new SyncAgent(clientProvider, serverProvider, tables);

// Using the Progress pattern to handle progession during the synchronization
var progress = new Progress<ProgressArgs>(s => Console.WriteLine($"[client]: {s.Context.SyncStage}:\t{s.Message}"));

do
{
    Console.Clear();
    Console.WriteLine("Sync Start");
    try
    {
        // Launch the sync process
        var s1 = await agent.SynchronizeAsync(progress);

        // Write results
        Console.WriteLine(s1);
    }
    catch (Exception e)
    {
        Console.WriteLine(e.Message);
    }


    //Console.WriteLine("Sync Ended. Press a key to start again, or Escapte to end");
} while (Console.ReadKey().Key != ConsoleKey.Escape);

Console.WriteLine("End");
```

And it worked. Here is the result

``` shell
Sync Start
[client]: BeginSession:
[client]: ScopeLoading: Id:fc3bc966-51db-43b9-a8d0-4f325f0a50bb LastSync: LastSyncDuration:0 SyncState:Successful
[client]: SchemaApplied:        Tables count:2
[client]: DatabaseTableApplied: TableName: ObjectSettingValues Provision:All
[client]: DatabaseApplied:      TableName: ObjectSettings Provision:All
[client]: DatabaseApplied:      Tables count:9 Provision:All
[client]: TableChangesSelected: ObjectSettings Inserts:0 Updates:0 Deletes:0 TotalChanges:0
[client]: TableChangesSelected: ObjectSettingValues Inserts:0 Updates:0 Deletes:0 TotalChanges:0
[client]: TableChangesApplied:  ObjectSettings State:Added Applied:1 Failed:0
[client]: TableChangesApplied:  ObjectSettingValues State:Added Applied:2 Failed:0
[client]: ScopeSaved:   Id:fc3bc966-51db-43b9-a8d0-4f325f0a50bb LastSync:06/02/2019 11:22:32 LastSyncDuration:41502695 SyncState:Successful
[client]: EndSession:
Synchronization done.
        Total changes downloaded: 3
        Total changes uploaded: 0
        Total conflicts: 0
        Total duration :0:0:4.150
```

**Comment by Thaval** [comment]
Thx for your rapid investigation. I gotta check this closer and figure out the differences that it works for you. I'll be posting as soon as I finished my investigation.

**Pull request merged**
