### PR TITLE
Speedup pipelines

### LINKED ISSUE #1167: Speed up pipelines
The pipelines could be optimized in some ways:

1) the SDKs can be downloaded only as needed, instead of downloading all 3 on every pipeline.

2) Nuget packages can be cached between builds instead of needing to be re-downloaded each time

3) Docker containers could be optimized so that only the correct docker container needed for each test is run

4) dotnet CLI usage could be optimized to prevent duplicate steps.

### PR DESCRIPTION
**Pull request by symbiogenesis**
This may go some ways towards speeding up the pipelines

I think it will save a couple minutes per pipeline. Refactoring the tests, as described in #1162 would help more substantially.

The cache step won't save any time on the first run, but subsequent runs will benefit.

Generating lockfiles was necessary in order to create a perfect cache key

Fixes #1167 and #1165

### CODE REVIEW

**Comment by symbiogenesis** [comment]
@Mimetis This should fix the pipelines and also improve them a bunch.

And it closes two of the issues I just opened, with some explanation.

**Comment by symbiogenesis** [comment]
@Mimetis this should make the pipelines green. I just resolved the conflicts from today.

**Comment by Mimetis** [comment]
@symbiogenesis  nice, I'll look this week end for sure

**Comment by Mimetis** [comment]
Hey @symbiogenesis , I'm struggling a little bit with the tests pipelines since this PR

Seems the tests are not run when targeting .net core 3.1
Seems the runner is not able to find the related tests:

```
No test matches the given testcase filter `Dotmim.Sync.Tests.SqlServerTcp` in 
/home/vsts/work/1/s/Tests/Dotmim.Sync.Tests/bin/Debug/netcoreapp3.1/Dotmim.Sync.Tests.dll
```

https://dev.azure.com/dotmim/Dotmim.Sync/_build/results?buildId=1631&view=logs&j=196c4937-6990-58b5-7d18-234ac2f0888b&t=45bab8b5-ece4-5e34-d7da-aaa6e8c8056a

Any idea ?

**Comment by Mimetis** [comment]
hum I don't know what I've done, but it's working now :)

**Pull request merged**
