### PR TITLE
81 virtual filters

### PR DESCRIPTION
**Pull request by gentledepp**
Adds the notion of virtual filters.
Fixes issue #81

### CODE REVIEW

**Comment by Mimetis** [comment]
Thx @gentledepp .

Is it working on MySQL as well ? (did not see any MySQL files changed in the PR)

Seb

**Comment by gentledepp** [comment]
No, not I wanted to hear your opinion veford I do a complete implementation.

**Comment by gentledepp** [comment]
I do not quite understand this. SqlDbType and DbType are used everywhere throughout Dotmim.Sync.Core and are part of netstandard. What am I missing here?

Are you planning to support other sync providers as well, which are not SQL-based? (couchdb, ravendb, filesystem, ...)?

**Comment by gentledepp** [comment]
Ok.. so I think I got your point.
I switched to DbType since it is also used in DmTable.
Is that ok with you? If 'yes', I'd provide a MySql implementation as well

**Comment by gentledepp** [comment]
@Mimetis 
As you probably remember, we are working on a better filter aproach (which i outlined a bit here: #2 )

Now we managed to put it to work.
You can actually have a look at a working Dotmim.Sync-based implementation in the following repository: https://github.com/gentledepp/SyncFilters

What it basically does is solve the "getting out of scope" problem of the old sync framework, so you can define very fine grained which user gets to see which rows - also based on permissions which may be totally independent from the base row that actually gets synchronized.

**Comment by Mimetis** [comment]
Ok let's go ! can I merge this branch or will you make the MySQL virtual filter soon ?

**Comment by gentledepp** [comment]
I am not sure when I can do the MySql provider - I have very little experience with MySql.
But I'll try my best.
We should always add all features to all providers, or API users will be very confused.

**Comment by gentledepp** [comment]
@Mimetis 
I have to revert my decision:
I just tried to implement those missing tests for virtual syncfitlers to mysql.

Doing that I found out, that there are no MySqlSyncFiltersTests yet, where the server itself is running MySql.

So I added them thinking that everything should work,  but it doesn't.
So I added another PR #87

It does not work yet - still so many exceptions. I would appreciate your help though, as I am an absolute MySql N00B!

So from my point of view, you can merge this branch now, as the basic syncfilter feature isn't provided for MySQL anyways. :-|

**Pull request merged**
