### PR TITLE
Fixes issues with tables that contain non-comparable columns

### PR DESCRIPTION
**Pull request by SvdSinner**
Fixes issues with tables that contain non-comparable columns (XML, TXT, NTEXT)

### CODE REVIEW

**Comment by SvdSinner** [comment]
I made these changes in a style to mimic existing code.  Feel welcome to tweak it, reformat it, etc. in any way you would like

**Comment by SvdSinner** [comment]
I'm not sure what to do with the failed MySql & MariaDB Tests.  This PR doesn't touch any of that functionality.  If I need to do something to fix these tests, please let me know.

**Comment by Mimetis** [comment]
Hey @SvdSinner 

I've reviewed your PR, and I think you've found a pretty interesting solution.
Indeed, there is some failed tests, but I'll fixes them, no worry

I've reviewed the SQL generated by the `GetChanges` stored proc and I remember now, why we have a `distinct` in the query.
It's only used when we have a filter associated with the query.

If there is no filter, there is no benefits to add a `distinct` to the `Select` clause (as the tracking table has a 1-1 relationship with its parent table)

I'm currently working on refactoring tests and some providers routine, but once it's done, I will work on your PR, to fix everything.

Thanks for this great solution to improve the support of old `text` and `ntext` fields! (That's being said, please... don't use them :D )

**Comment by SvdSinner** [comment]
I realized there were some bugs in the ChangeTracking project that this caused.  There is now a new commit that fixes the 3 typos that caused the bugs.

**Comment by Mimetis** [comment]
Hey @SvdSinner 

Sorry to come back to you so late.
I was struggling with the refactor of all the tests and the integration of the `Postgres` provider.

I've made some adjustments in the `GetChanges` stored procedures generation for **SQL Server**.
Can you update your **PR** to resolve the conflicts and be sure your adjustments for `"Xml", "Text", "NText"` are generated only when `filter != null` ? 

Once it's done, I will make the rights adjustments to integrate the corresponding's tests and be sure it's working fine with all the other providers.

Thanks a ton for your contribution!

**Comment by Mimetis** [comment]
Thanks !
I will make the relevant tests before the next release

**Comment by Mimetis** [comment]
I'm sorry @SvdSinner, I had to revert back your PR (see #936 ) as all tests are failing.

**Pull request merged**
