### PR TITLE
Minor fixes

### PR DESCRIPTION
**Pull request by vunder**
Fixes in RyncResults that may cause debug errors because NullReferenceException
AfterDeserializedRows was not called while HTTP-sync
Correct sync on server in case there is not body hash in request headers

### CODE REVIEW

**Comment by vunder** [comment]
I see that few tests are falling because of error in `DateConverter.AfterDeserialized` that should convert ticks to DateTime. But in fact, values there are DateTime instead of Int64

**Comment by Mimetis** [comment]
Thanks a ton @vunder for these fixes !!

**Comment by Mimetis** [comment]
BTW, I found the bug on Converter :)

**Comment by vunder** [comment]
@Mimetis Yes, that's why some tests are failing. And I wrote about it.
There are unit tests for data conversion. However, `DateConverter` in tests does not consider that

**Comment by Mimetis** [comment]
I missed a serialization process in a specific case, that should fine now :)
Thanks again for the various fixes, it's helping a lot !!!

**Pull request merged**
